url: https://staticmapmaker.com
permalink: /:title/
author:
  name: Katy DeCorah
  email: katydecorah@gmail.com
  uri: https://katydecorah.com
  twitter: katydecorah

title: Static Map Maker
description: "Create a Bing static map, Google static map, Mapbox static map, MapQuest static map, a HERE static map, a CartoDB static map, or a Yandex static map. Type in a location, customize, and get the map."

port: 4000
host: 127.0.0.1

# these will rotate
mapquestKey: HkQT4BGfQ9clGrwhLknjPxeF08UZ3k9K
bingKey: Ah12kIOAYzmW3ONiCcYEImWIp2xL8pwMXEvlOjhzjLRhjBBOCgBygJe4PHOY_aKU
hereappid: Aa1YIIyNYjkb6oaXEBL4
herecodeid: pVymqwwjz2o0icg1RF78OQ

exclude:
  - vendor
  - .sass-cache
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - test

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-feed

angularjs: 1.6.1
jquery: 3.2.1

# adsense
client: ca-pub-5924879737462180
slot: 3966465755

sass:
  style: :compressed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "page"
