name: Static Map Maker
description: "Create a Bing static map, Google static map, Mapbox static map, MapQuest static map, a HERE static map, a CartoDB static map, or a Yandex static map. Type in a location, customize, and get the map."
url: http://staticmapmaker.com
#url: http://localhost:4000
permalink: /:title/

port: 4000
host: 127.0.0.1

# these will rotate
mapquestKey: HkQT4BGfQ9clGrwhLknjPxeF08UZ3k9K
bingKey: Ag5uuxO0xffGEd9QQ5vIaOp_f1KlwIycTPD4dLaYGHdfwkr5QP-lTIXwZE-_2oos
hereappid: Aa1YIIyNYjkb6oaXEBL4
herecodeid: pVymqwwjz2o0icg1RF78OQ

exclude:
- vendor
- .sass-cache
- CNAME
- README.md
- Gemfile
- node_modules

gems:
- jekyll-sitemap
- jekyll-redirect-from
- jemoji

angularjs: 1.4.8
jquery: 2.1.4

sass:
 style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "page"
